set(SRC_FILES
    App.cpp
    GameSession.cpp
    LevelManager.cpp
    MapTiles.cpp
    Player.cpp
    PlayerBounce.cpp
    Bomb.cpp
    Explosion.cpp
    BombManager.cpp
    InteractableManager.cpp
    Interactable.cpp
    AIManager.cpp
    Bot/BotNavigator.cpp
    DangerMap.cpp
    CheatManager.cpp
    Menu.cpp
    PauseMenu.cpp
    GameWorldContext.cpp
    UI/UIManager.cpp
    UI/UIImage.cpp
    UI/UIText.cpp
    UI/UIButtonList.cpp
    Spirit.cpp
    Turret/Projectile.cpp
    Turret/TurretManager.cpp
    Turret/Turret.cpp
)

set(INCLUDE_FILES
    App.hpp
    GameSession.hpp
    GameConstants.hpp
    GameTypes.hpp
    MatchConfig.hpp
    GridCoord.hpp
    LevelManager.hpp
    MapTiles.hpp
    TileSet.hpp
    Player.hpp
    PlayerBounce.hpp
    Bomb.hpp
    Explosion.hpp
    BombManager.hpp
    InteractableManager.hpp
    Interactable.hpp
    AIManager.hpp
    Bot/BotNavigator.hpp
    DangerMap.hpp
    CheatManager.hpp
    Menu.hpp
    PauseMenu.hpp
    Controller/InputController.hpp
    Controller/HumanController.hpp
    Controller/BotController.hpp
    Controller/IProgrammableController.hpp
    Effects/IPlayerEffect.hpp
    Effects/PlayerEffects.hpp
    WorldContext.hpp
    GameWorldContext.hpp
    UI/UIManager.hpp
    UI/UIImage.hpp
    UI/UIText.hpp
    UI/UIButtonList.hpp
    Spirit.hpp
    Turret/Projectile.hpp
    Turret/TurretManager.hpp
    Turret/Turret.hpp
)

set(TEST_FILES
)
