set(SRC_FILES
    App.cpp
    LevelManager.cpp
    MapTiles.cpp
    Player.cpp
    Bomb.cpp
    Explosion.cpp
    BombManager.cpp
    InteractableManager.cpp
    Interactable.cpp
    UIManager.cpp
    AIManager.cpp
    Menu.cpp
    GameWorldContext.cpp
)

set(INCLUDE_FILES
    App.hpp
    BackgroundImage.hpp
    LevelManager.hpp
    MapTiles.hpp
    Player.hpp
    Bomb.hpp
    Explosion.hpp
    BombManager.hpp
    InteractableManager.hpp
    Interactable.hpp
    ScreenImage.hpp
    UIManager.hpp
    AIManager.hpp
    Menu.hpp
    Controller/InputController.hpp
    Controller/HumanController.hpp
    Controller/BotController.hpp
    WorldContext.hpp
    GameWorldContext.hpp
)

set(TEST_FILES
)
